name: 'RPM Build'
description: 'Build RPMs from spec file and upload it as Artifact or Release Asset'
author: 'Naveenraj M'

inputs: 
  spec_file:
    description: 'path to the spec file'
    required: true
    default: '*.spec'                     #Any spec file in top 
  additional_repos:
    description: 'A list of additional repositories to install'
    required: false
    default: none
  enable_repos:
    description: 'A list of additional repositories to enable'
    requires: false
    default: none
  enable_modules:
    description: 'A list of dnf modules to enable'
    required: false
    default: none
  disable_modules:
    description: 'A list of dnf modules to disable'
    requires: false
    default: none
outputs:
  source_rpm_path:
    description: 'path to Source RPM file'
  source_rpm_dir_path:
    description: 'path to  SRPMS directory'
  source_rpm_name:
    description: 'name of Source RPM file'
  rpm_dir_path:
    description: 'path to RPMS directory'
  rpm_content_type:
    description: 'Content-type for Upload'

runs:
  using: 'composite'
  steps:
    - run: echo Building spec ${{ inputs.spec_file }}
      shell: bash
    - run: ls ${GITHUB_ACTION_PATH}
      shell: bash
    - run: sh ${GITHUB_ACTION_PATH}/entrypoint.sh ${{ inputs.spec_file }}  ${{ inputs.additional_repos }} ${{ inputs.enabled_repos }} ${{ inputs.enable_modules }} ${{ inputs.disable_modules }}
      shell: bash

branding:
  icon: 'package'
  color: 'red'

  
